### ISSUE TITLE
Error when restarting sbot server after plugin installs

### ISSUE THREAD

**Issue by austinfrey** [ssbc/patchlite#3]
I'm getting this error when restarting the server after installing the ssb-links plugin
`Error: plugin at:ssb-links expected name:links but had:links2`

and also this error after the ssb-query and ssb-ws plugins
`Error: already loaded plugin named:query`
`Error: already loaded plugin named:ws`

Just to get things running, I manually updated the `links` file and changed the name from `links2` to `links` and simply omitted the `query` and `ws` plugins. I was able to load patchlite inthe browser then, but it wasn't functional. Any thoughts? If additional info is needed, let me know. Thanks!

**Comment by ahdinosaur** [comment]
thanks for the issue @aafrey. this might be tricky to fix standalone, but you can try to use `scuttlebot@9` instead of the latest.

for context: at the moment, `patchlite` is out of date from [`patchbay`](https://github.com/ssbc/patchbay) (due to the inclusion of css styles and fonts in a way that was incompatible with the browser) and the rest of the ssb ecosystem, which is leading to [`scuttlebot@10`](https://github.com/ssbc/scuttlebot) plugins being incompatible.

i spent a chunk of time working on [`require-style`](https://github.com/ahdinosaur/require-style) which targets the reason we can't use the latest `patchbay`, which should theoretically work but i never tested it: https://github.com/ssbc/patchbay/pull/117. lately i've been busy with other things. want to help push this forward?

**Comment by ahdinosaur** [comment]
also @aafrey, in the meantime until #4 is done, if you want a lite client in the browser i can recommend [`minbay`](https://github.com/evbogue/minbay) or [`patchfoo`](https://git.scuttlebot.io/%25YAg1hicat%2B2GELjE2QJzDwlAWcx0ML%2B1sXEdsWwvdt8%3D.sha256) :+1:

**Comment by austinfrey** [comment]
@ahdinosaur thanks! also, i'd be willing to pitch in where I can, but it might take me some time to familiarize myself with things. 

Thanks for the quick responses

**Comment by acailly** [comment]
Sorry to dig this issue but it is the only issue I found about the error `expected name:links but had:links2`.

To other fellows having this error message and wondering how to resolve it, what worked for me is I simply edited my config with `"ssb-links": false` instead of `"ssb-links": true` and it seems to work.
